apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: between

resources:
  - ../../base

images:
  - name: ghcr.io/dakshbhavsar007/between-backend
    newTag: dev-latest
  - name: ghcr.io/dakshbhavsar007/between-frontend
    newTag: dev-latest
