apiVersion: v1
kind: Service
metadata:
  name: between-backend
  namespace: between
  labels:
    app: between-backend
    app.kubernetes.io/name: between
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
      protocol: TCP
  selector:
    app: between-backend
