apiVersion: v1
kind: ConfigMap
metadata:
  name: between-config
  namespace: between
  labels:
    app.kubernetes.io/name: between
    app.kubernetes.io/part-of: between-gitops
data:
  DEBUG: "False"
  PORT: "8000"
  ALLOWED_ORIGINS: "http://localhost:3000,http://13.201.134.20,https://between.dakshaws.sryze.cc,http://between.dakshaws.sryze.cc,https://between.indevs.in"
  UPLOAD_DIR: "/app/uploads"
  PHOTO_DIR: "/app/photos"
  POSTGRES_PORT: "5432"
  REDIS_PORT: "6379"
