apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: between-uploads-pvc
  namespace: between
  labels:
    app.kubernetes.io/name: between
    app.kubernetes.io/part-of: between-gitops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
