apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: between

resources:
  - ../../base

# Immutable image references published in Phase 4 to GHCR
images:
  - name: ghcr.io/dakshbhavsar007/between-backend
    newTag: 26bd061
  - name: ghcr.io/dakshbhavsar007/between-frontend
    newTag: 26bd061
